# fly.toml app configuration file generated for coin-funds on 2023-05-21T04:22:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coin-funds"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
